version: '3.7'
services:
  frontend:
    build: './frontend'
    container_name: 'frontend'
    depends_on:
      - backend
    volumes:
      - ./frontend:/opt/app
    environment:
      PORT: ${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: 'backend'
    depends_on:
      - postgres
    volumes:
      - ./backend:/opt/app
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # volumes:
    # - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
volumes:
  postgres:
