version: '3.7'
services:
  frontend:
    build: './frontend'
    container_name: 'frontend'
    depends_on:
      - backend
    volumes:
      - ./frontend:/opt/app
    environment:
      PORT: ${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  backend:
    build: './backend'
    container_name: 'backend'
    depends_on:
      - mongo
    volumes:
      - ./backend:/opt/app
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  mongo:
    image: mongo:latest
    restart: always
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

volumes:
  mongodata:
