version: '3.7'
services:
  frontend-test:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.test
    container_name: 'frontend-test'
    depends_on:
      - backend-test
    volumes:
      - ./frontend:/opt/app
    environment:
      PORT: ${FRONTEND_PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  backend-test:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.test
    container_name: 'backend-test'
    depends_on:
      - mongo-test
    volumes:
      - ./backend:/opt/app
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URL: mongodb://mongo-test:${MONGO_PORT}/${MONGO_INITDB_DATABASE}
      NODE_ENV: ${NODE_ENV}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  mongo-test:
    image: mongo:latest
    restart: always
    container_name: 'mongo-test'
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
